trigger:
- main  # Cambia 'main' si tu rama se llama diferente

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Login to DockerHub
  inputs:
    command: login
    containerRegistry: dockerhub-frpatino6  # Usa el nombre de tu Service Connection

- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    tags: |
      frpatino6/redis-dispatcher:latest

- task: Docker@2
  displayName: Push Docker Image
  inputs:
    command: push
    tags: |
      frpatino6/redis-dispatcher:latest
